### ISSUE TITLE
[BUG] Unable to build

### ISSUE THREAD

**Issue by Samuka007** [BrahmaMantra/book-hub-front#5]
`npm run build` failed. Output:

```
useSearchParams() should be wrapped in a suspense boundary at page "/callback". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at a (/workspaces/ModernLibre-front/.next/server/chunks/860.js:1:17900)
    at d (/workspaces/ModernLibre-front/.next/server/chunks/860.js:1:30998)
    at a (/workspaces/ModernLibre-front/.next/server/app/callback/page.js:1:2188)
    at nj (/workspaces/ModernLibre-front/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:45788)
    at nO (/workspaces/ModernLibre-front/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:47563)
    at nN (/workspaces/ModernLibre-front/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:65362)
    at nM (/workspaces/ModernLibre-front/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:62993)
    at n$ (/workspaces/ModernLibre-front/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:46140)
    at nO (/workspaces/ModernLibre-front/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:47609)
    at nO (/workspaces/ModernLibre-front/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:62344)
Error occurred prerendering page "/callback". Read more: https://nextjs.org/docs/messages/prerender-error
```

cc? @xiaolin2004

**Comment by Samuka007** [comment]
fix in e2883695b918b56d7e91d75184c6ed20f83bb5ef
